# Generated by Django 3.2.3 on 2021-05-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('m', 'marked'), ('u', 'unmarked')], default='u', max_length=1),
        ),
    ]
